using System;
using System.Collections.Generic;
using System.Text;

namespace Sun.RDS.Sync.DataAccess.Query
{
    public static class TransSQL
    {
        #region GET Query
        public const string GET_BY_ID = " SELECT * FROM trans WHERE TransID = @TransID;";
        #endregion

        #region DML Query
        public const string INSERT_TRANS = " INSERT INTO trans(TransID,TransNo,TermID,TransDate,LastDate,TransTime,CustomerNumber,CashierID,CashierName,SalesPersonID,SalesPersonName,HasSalesMan,SubTotal,TaxAmount1,TaxAmount2,TaxAmount3,TaxAmount4,TaxAmount5,TaxAmount6,Total,DiscType,DiscAmount,DiscValue,Points,TransStatus,ManualKey,CheckOut,Round,MemberDiscAmount,MemberDiscValue,BirthDayDiscAmount,BirthDayDiscValue,SCDiscAmount,SCDiscValue,SCCovers,SCRetTaxAmount,ASDiscAmount,ASDiscValue,Printed,Covers,Notes,PaidTotal,TimeStampId,BusinessDate,VoucherTotal,RDPointsTotal,RDFlag,RDPointsAmount,RDPointValue,TableMenuID,DeliverCustNo,PDDiscAmount,PDDiscValue,PDCovers,GERetTaxAmount,GECovers,ManagerID,ManagerName,SendFlag,EditTransID,OrderID,SplitBill,DueDays,DueType,PreviousPoints,KDSOrderStatus,KDSPriority,KDSCmptTime,PDRetTaxAmount,DOaddress,PrintHold,AdvCustomerID,AdvCountryCode,AdvSVBal,AdvVBal,AdvLPoints,AdvLLPoints,AdvLPID,AdvLPRID,AdvSKURID,AdvCashBack,AdvLCashBack,AdvCBID,AdvCBRID,STBCPPrev,STBCPBal,Userid,OlStatus,DeliveryDate)VALUES(@TransID,@TransNo,@TermID,@TransDate,@LastDate,@TransTime,@CustomerNumber,@CashierID,@CashierName,@SalesPersonID,@SalesPersonName,@HasSalesMan,@SubTotal,@TaxAmount1,@TaxAmount2,@TaxAmount3,@TaxAmount4,@TaxAmount5,@TaxAmount6,@Total,@DiscType,@DiscAmount,@DiscValue,@Points,@TransStatus,@ManualKey,@CheckOut,@Round,@MemberDiscAmount,@MemberDiscValue,@BirthDayDiscAmount,@BirthDayDiscValue,@SCDiscAmount,@SCDiscValue,@SCCovers,@SCRetTaxAmount,@ASDiscAmount,@ASDiscValue,@Printed,@Covers,@Notes,@PaidTotal,@TimeStampId,@BusinessDate,@VoucherTotal,@RDPointsTotal,@RDFlag,@RDPointsAmount,@RDPointValue,@TableMenuID,@DeliverCustNo,@PDDiscAmount,@PDDiscValue,@PDCovers,@GERetTaxAmount,@GECovers,@ManagerID,@ManagerName,@SendFlag,@EditTransID,@OrderID,@SplitBill,@DueDays,@DueType,@PreviousPoints,@KDSOrderStatus,@KDSPriority,@KDSCmptTime,@PDRetTaxAmount,@DOaddress,@PrintHold,@AdvCustomerID,@AdvCountryCode,@AdvSVBal,@AdvVBal,@AdvLPoints,@AdvLLPoints,@AdvLPID,@AdvLPRID,@AdvSKURID,@AdvCashBack,@AdvLCashBack,@AdvCBID,@AdvCBRID,@STBCPPrev,@STBCPBal,@Userid,@OlStatus,@DeliveryDate);";

        public static string INSERT_TRANSDETAIL = @"INSERT INTO transdetail(TransID,ItemID,BarCode,Name,InventoryDesc,StockCode,Void,NoPriceShift,CategoryNumber,Group1,Group2,Group3,Group4,Group5,Class,Qty,Unit,PriceType,Price,ActualPrice,Amount,ShiftMixedFlag,QuantityShiftType,ShiftValue,OddDisc,RealPrice,QuantityFrom,Description,DiscQty,PSDiscAmount,PSDiscValue,ActualPSDiscAmount,QtyRemain,TotalSoldQty,TotalDiscQty,DiscType,DiscValue,ManualDisc,Points,Checkout,TakeAway,MemberDisc,SalesMan,OrderTime,Printed,BufferPrinted,PriceID,Condimented,KitchenPrint,KitchenPrintFlag,TaxAmount1,TaxAmount2,TaxAmount3,TaxAmount4,TaxAmount5,TaxAmount6,ItemStatus,TaxableAmount,TaxFlag,TaxInfo,ParentID,PrintedVoid,VoidDate,AllowDecimalValue,TotalDisc,TotalMemberDisc,TotalPSDisc,RDPoints,ItemSCDiscAmount,ItemSCDiscValue,ItemSCCovers,ItemSCRetTaxAmount,Warranty,UnitCost,ManagerID,ManagerName,KitchenStatus,FireQuantity,Commission,CommissionValue,KDSItemStatus,KDSDoneQty,KDSItemPriority,KDSItemCmptTime,MParentID,MChildID)VALUES(@TransID,@ItemID,@BarCode,@Name,@InventoryDesc,@StockCode,@Void,@NoPriceShift,@CategoryNumber,@Group1,@Group2,@Group3,@Group4,@Group5,@Class,@Qty,@Unit,@PriceType,@Price,@ActualPrice,@Amount,@ShiftMixedFlag,@QuantityShiftType,@ShiftValue,@OddDisc,@RealPrice,@QuantityFrom,@Description,@DiscQty,@PSDiscAmount,@PSDiscValue,@ActualPSDiscAmount,@QtyRemain,@TotalSoldQty,@TotalDiscQty,@DiscType,@DiscValue,@ManualDisc,@Points,@Checkout,@TakeAway,@MemberDisc,@SalesMan,@OrderTime,@Printed,@BufferPrinted,@PriceID,@Condimented,@KitchenPrint,@KitchenPrintFlag,@TaxAmount1,@TaxAmount2,@TaxAmount3,@TaxAmount4,@TaxAmount5,@TaxAmount6,@ItemStatus,@TaxableAmount,@TaxFlag,@TaxInfo,@ParentID,@PrintedVoid,@VoidDate,@AllowDecimalValue,@TotalDisc,@TotalMemberDisc,@TotalPSDisc,@RDPoints,@ItemSCDiscAmount,@ItemSCDiscValue,@ItemSCCovers,@ItemSCRetTaxAmount,@Warranty,@UnitCost,@ManagerID,@ManagerName,@KitchenStatus,@FireQuantity,@Commission,@CommissionValue,@KDSItemStatus,@KDSDoneQty,@KDSItemPriority,@KDSItemCmptTime,@MParentID,@MChildID);";

        public static string UPDATE_TRANS = @"UPDATE trans SET TransNo = @TransNo, TermID = @TermID, TransDate = @TransDate, LastDate = @LastDate, TransTime = @TransTime, CustomerNumber = @CustomerNumber, CashierID = @CashierID, CashierName = @CashierName, SalesPersonID = @SalesPersonID, SalesPersonName = @SalesPersonName, HasSalesMan = @HasSalesMan, SubTotal = @SubTotal, TaxAmount1 = @TaxAmount1, TaxAmount2 = @TaxAmount2, TaxAmount3 = @TaxAmount3, TaxAmount4 = @TaxAmount4, TaxAmount5 = @TaxAmount5, TaxAmount6 = @TaxAmount6, Total = @Total, DiscType = @DiscType, DiscAmount = @DiscAmount, DiscValue = @DiscValue, Points = @Points, TransStatus = @TransStatus, ManualKey = @ManualKey, CheckOut = @CheckOut, Round = @Round, MemberDiscAmount = @MemberDiscAmount, MemberDiscValue = @MemberDiscValue, BirthDayDiscAmount = @BirthDayDiscAmount, BirthDayDiscValue = @BirthDayDiscValue, SCDiscAmount = @SCDiscAmount, SCDiscValue = @SCDiscValue, SCCovers = @SCCovers, SCRetTaxAmount = @SCRetTaxAmount, ASDiscAmount = @ASDiscAmount, ASDiscValue = @ASDiscValue, Printed = @Printed, Covers = @Covers, Notes = @Notes, PaidTotal = @PaidTotal, TimeStampId = @TimeStampId, BusinessDate = @BusinessDate, VoucherTotal = @VoucherTotal, RDPointsTotal = @RDPointsTotal, RDFlag = @RDFlag, RDPointsAmount = @RDPointsAmount, RDPointValue = @RDPointValue, TableMenuID = @TableMenuID, DeliverCustNo = @DeliverCustNo, PDDiscAmount = @PDDiscAmount, PDDiscValue = @PDDiscValue, PDCovers = @PDCovers, GERetTaxAmount = @GERetTaxAmount, GECovers = @GECovers, ManagerID = @ManagerID, ManagerName = @ManagerName, SendFlag = @SendFlag, EditTransID = @EditTransID, OrderID = @OrderID, SplitBill = @SplitBill, DueDays = @DueDays, DueType = @DueType, PreviousPoints = @PreviousPoints, KDSOrderStatus = @KDSOrderStatus, KDSPriority = @KDSPriority, KDSCmptTime = @KDSCmptTime, PDRetTaxAmount = @PDRetTaxAmount, DOaddress = @DOaddress, PrintHold = @PrintHold, AdvCustomerID = @AdvCustomerID, AdvCountryCode = @AdvCountryCode, AdvSVBal = @AdvSVBal, AdvVBal = @AdvVBal, AdvLPoints = @AdvLPoints, AdvLLPoints = @AdvLLPoints, AdvLPID = @AdvLPID, AdvLPRID = @AdvLPRID, AdvSKURID = @AdvSKURID, AdvCashBack = @AdvCashBack, AdvLCashBack = @AdvLCashBack, AdvCBID = @AdvCBID, AdvCBRID = @AdvCBRID, STBCPPrev = @STBCPPrev, STBCPBal = @STBCPBal, Userid = @Userid, OlStatus = @OlStatus, DeliveryDate = @DeliveryDate WHERE TransID = @TransID;";

        public static string DELETE_TRANSDETAIL = @"DELETE FROM transdetail WHERE  TransID = @TransID;";

        #endregion
    }
}
